/* BUILT 2026-09-11 · park 1a
   ============================================================================
   THE PARKING WORKER — every domain in the Wall St Domains inventory points
   here. Whoever types goodsolar.com lands on that name's page on
   wallstdomains.com, with its story, price and the Buy button — instead of
   the registrar's parking junk.

   Any hostname routed to this worker is sent to
     https://wallstdomains.com/domain/<name as stored>
   The marketplace looks the name up EXACTLY as stored (mixed case and all),
   so the table below carries the stored spelling. A host not in the table
   goes to the marketplace home page rather than to a "not found".

   Nothing is served from the parked domain itself; it is a redirect, so the
   marketplace stays the one place a name is described.
   ============================================================================ */
const NAMES = {
  "66kt.com": "66KT.COM",
  "66kt.org": "66kt.org",
  "66kt.us": "66kt.us",
  "84domains.com": "84domains.com",
  "adhotbox.com": "ADHOTBOX.COM",
  "aqua-tru.com": "AQUA-TRU.COM",
  "atomwatt.com": "ATOMWATT.COM",
  "atomwatt.org": "atomwatt.org",
  "atomwatts.com": "atomwatts.com",
  "atom-watts.com": "atom-watts.com",
  "atomwatts.org": "atomwatts.org",
  "atomwatts.us": "atomwatts.us",
  "bayonneroofrepair.com": "BAYONNEROOFREPAIR.COM",
  "benchpresscontest.com": "BENCHPRESSCONTEST.COM",
  "bidappy.com": "bidappy.com",
  "bookraffle.com": "BOOKRAFFLE.COM",
  "colorappy.com": "colorappy.com",
  "comedyisnews.com": "COMEDYISNEWS.COM",
  "comedyisnews.net": "comedyisnews.net",
  "continentalroofsystems.com": "CONTINENTALROOFSYSTEMS.COM",
  "corruptmen.com": "CORRUPTMEN.COM",
  "datalola.com": "DATALOLA.COM",
  "dataloli.com": "DATALOLI.COM",
  "downsyndromedia.com": "downsyndromedia.com",
  "dummydomain.com": "dummydomain.com",
  "fidgetroom.com": "FIDGETROOM.COM",
  "fitnesspro.app": "FitnessPro.app",
  "freakshoe.com": "FREAKSHOE.COM",
  "gas2water.com": "gas2water.com",
  "getitupamerica.com": "getitupamerica.com",
  "gogohose.com": "GOGOHOSE.COM",
  "gogoscrew.com": "GOGOSCREW.COM",
  "goodsolar.ca": "GOODSOLAR.CA",
  "goodsolar.com": "GOODSOLAR.COM",
  "goodsolar.net": "GOODSOLAR.NET",
  "goodsolar.org": "GOODSOLAR.ORG",
  "goodsolar.us": "GOODSOLAR.US",
  "grandmacheerleaders.com": "grandmacheerleaders.com",
  "greenenergy.co": "GreenEnergy.co",
  "h2ofuels.com": "h2ofuels.com",
  "hardcloth.com": "Hardcloth.com",
  "hikersball.com": "HIKERSBALL.COM",
  "hobokenroofrepair.com": "HOBOKENROOFREPAIR.COM",
  "ineedagoodtherapist.com": "INEEDAGOODTHERAPIST.COM",
  "jackraffle.com": "JACKRAFFLE.COM",
  "jerseycitymason.com": "JERSEYCITYMASON.COM",
  "jerseycityroofer.com": "JERSEYCITYROOFER.COM",
  "jerseycityroofrepair.com": "JERSEYCITYROOFREPAIR.COM",
  "jerseyshorecontractor.com": "JERSEYSHORECONTRACTOR.COM",
  "jerseyshorecontractors.com": "JERSEYSHORECONTRACTORS.COM",
  "jerseyshoremason.com": "JERSEYSHOREMASON.COM",
  "jerseyshoreroofrepair.com": "jerseyshoreroofrepair.com",
  "jobcreation.us": "JOBCREATION.US",
  "jobcreationdefinition.com": "JOBCREATIONDEFINITION.COM",
  "lacasatriste.com": "lacasatriste.com",
  "lasvegasroofrepair.com": "lasvegasroofrepair.com",
  "liftamericaup.com": "LIFTAMERICAUP.COM",
  "littleroofs.com": "LITTLEROOFS.COM",
  "magkinetics.com": "MAGKINETICS.COM",
  "manofegg.com": "MANOFEGG.COM",
  "mojoping.com": "MOJOPING.COM",
  "mrjobcreation.com": "MRJOBCREATION.COM",
  "musicinnews.com": "musicinnews.com",
  "musicisnew.com": "musicisnew.com",
  "musicisnews.com": "MUSICISNEWS.COM",
  "musicisnews.net": "musicisnews.net",
  "musicisnews.org": "musicisnews.org",
  "mycustomerinformation.com": "MYCUSTOMERINFORMATION.COM",
  "newsweed.com": "NEWSWEED.COM",
  "newsweed.net": "newsweed.net",
  "newsweed.org": "newsweed.org",
  "newsweed.us": "NEWSWEED.US",
  "newsweeds.com": "newsweeds.com",
  "newsweedstocks.com": "newsweedstocks.com",
  "newsworkcity.com": "NEWSWORKCITY.COM",
  "newsyorkcity.com": "NEWSYORKCITY.COM",
  "nft300.com": "nft300.com",
  "nft400.com": "nft400.com",
  "nft48.com": "nft48.com",
  "nft600.com": "nft600.com",
  "nft700.com": "nft700.com",
  "nft737.com": "nft737.com",
  "nft747.com": "nft747.com",
  "nft84.com": "nft84.com",
  "nft85.com": "nft85.com",
  "nft87.com": "nft87.com",
  "nft900.com": "nft900.com",
  "nft92.com": "nft92.com",
  "nft93.com": "nft93.com",
  "nft94.com": "nft94.com",
  "nft96.com": "nft96.com",
  "nft98.com": "nft98.com",
  "nftchord.com": "nftchord.com",
  "nftscrew.com": "nftscrew.com",
  "noticiasnews.com": "NOTICIASNEWS.COM",
  "nuevanoticias.com": "NUEVANOTICIAS.COM",
  "nujabee.com": "NUJABEE.COM",
  "nujabes.com": "NUJABES.COM",
  "nujabi.com": "NUJABI.COM",
  "nujabis.com": "NUJABIS.COM",
  "nujaby.com": "NUJABY.COM",
  "nujobi.com": "NUJOBI.COM",
  "nycfraudaudit.com": "NYCFRAUDAUDIT.COM",
  "nycroofrepairs.com": "NYCROOFREPAIRS.COM",
  "p2logic.com": "P2LOGIC.COM",
  "p2logic.org": "P2LOGIC.ORG",
  "patersonroofrepair.com": "PATERSONROOFREPAIR.COM",
  "princetonroofrepair.com": "princetonroofrepair.com",
  "realbuilder.co": "realbuilder.co",
  "realbuilder.us": "REALBUILDER.US",
  "realroofer.co": "REALROOFER.CO",
  "realroofer.co.uk": "REALROOFER.CO.UK",
  "realroofer.com": "REALROOFER.COM",
  "realroofer.info": "REALROOFER.INFO",
  "realroofer.net": "REALROOFER.NET",
  "realroofer.org": "REALROOFER.ORG",
  "realroofers.co": "REALROOFERS.CO",
  "realroofers.co.uk": "REALROOFERS.CO.UK",
  "realroofers.com": "REALROOFERS.COM",
  "real-roofers.com": "real-roofers.com",
  "realroofers.es": "realroofers.es",
  "realroofers.net": "REALROOFERS.NET",
  "realroofers.org": "REALROOFERS.ORG",
  "realroofersllc.com": "realroofersllc.com",
  "rooferschool.com": "ROOFERSCHOOL.COM",
  "roofinspectionservice.com": "roofinspectionservice.com",
  "roofleak.co": "roofleak.co",
  "roofleakemergency.com": "ROOFLEAKEMERGENCY.COM",
  "roofrepair24hours.com": "ROOFREPAIR24HOURS.COM",
  "roofrepairco.com": "roofrepairco.com",
  "roofrepairco.net": "roofrepairco.net",
  "roofrepairco.us": "roofrepairco.us",
  "roofrepairemergency.com": "ROOFREPAIREMERGENCY.COM",
  "roofrepairnyc.com": "ROOFREPAIRNYC.COM",
  "roofrepairs.us": "roofrepairs.us",
  "secretsss.com": "secretsss.com",
  "shoeraffle.com": "SHOERAFFLE.COM",
  "sidingup.com": "sidingup.com",
  "siliconroofing.com": "siliconroofing.com",
  "tattooisnews.com": "TATTOOISNEWS.COM",
  "technicallyjournalism.com": "TECHNICALLYJOURNALISM.COM",
  "thehikersball.com": "THEHIKERSBALL.COM",
  "thepregameshow.com": "thepregameshow.com",
  "theroofrepairco.com": "theroofrepairco.com",
  "timeappy.com": "Timeappy.com",
  "tinyhousers.com": "TINYHOUSERS.COM",
  "tinyroof.com": "TINYROOF.COM",
  "tinyroofer.com": "TINYROOFER.COM",
  "tinyroofs.com": "TINYROOFS.COM",
  "trailshrink.com": "trailshrink.com",
  "trailshrinks.com": "trailshrinks.com",
  "trumagoo.com": "TRUMAGOO.COM",
  "uglystartup.com": "UGLYSTARTUP.COM",
  "unionroofrepair.com": "UNIONROOFREPAIR.COM",
  "upyours.us": "upyours.us",
  "wallstdomain.com": "wallstdomain.com",
  "wallstdomains.com": "wallstdomains.com",
  "workappy.com": "workappy.com"
};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const host = url.hostname.toLowerCase().replace(/^www\./, "");
    const stored = NAMES[host];
    const to = stored
      ? "https://wallstdomains.com/domain/" + encodeURIComponent(stored)
      : "https://wallstdomains.com/?from=" + encodeURIComponent(host);
    return new Response(null, { status: 302, headers: {
      "Location": to,
      "Cache-Control": "no-store",
      "X-Parked-By": "wallstdomains.com"
    } });
  }
};